Algoritmo "Aula - idade"


Var

    idade : inteiro

Inicio

    escreva("Qual sua idade? R: ")
    leia(idade)
    
      se (idade >= 50 ) entao
      
         escreval
         escreval("Parabens! Você já pode ser Vacinado")
         
      senao
         escreval
         escreval("Desculpe! VocÊ terá que aguardar sua vez")
      
      fimse
    
    
    
    
    escreval
    escreval("Obrigado por acessar o sistema")
Fimalgoritmo