Algoritmo "Numero inteiros descrescente de 100 a 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Escreva um algoritmo que imprima todos os numeros
// descrescente e inteiros de 100 a 1.
Var
// Seção de Declarações das variáveis 
 i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i <- 100
enquanto i > 0 faça
     escreval("numero: ", i)
     i <- i - 1
fimenquanto
escreval("Fim do algoritmo")

Fimalgoritmo
